---
    -
        type: page
        template: ~/core/index
        route: /
        state: published
        layout:
            type: Fields
            title: Welcome to Lackey
            subtitle: A new breed of CMS
            blocks:
                type: List
                items:
                    -
                        type: Block
                        template: ~/core/partials/block/signup-demo
                        fields:
                            title: Contact us for a **free** personal demo of the Lackey CMS
                        props:
                            namePlaceholder: Name
                            emailPlaceholder: Email
                            buttonLabel: Send me my link!

                    -
                        type: Block
                        template: ~/core/partials/block/copy-media
                        fields:
                            title: For Content Admins
                            subtitle: Easy to use and difficult to break.
                            copy: |
                                Lackey facilitates the Client / Agency relationship, enforcing design rules and keeping admin users on a need to know basis. No dev stuff. It’s simple, focused &amp; consistent. Most CMS's let admins pick fonts, add hex ref colours, write HTML tags, and inject content in situations where it was never intended to go. Lackey gives admins just enough power and an easy life.
                            image:
                                type: Media
                                source: img/core/lackey-cms-screenshot-1.png
                        props:
                            theme: white
                            imageAlignment: side

                    -
                        type: Block
                        template: ~/core/partials/block/copy-media
                        fields:
                            title: Power for developers
                            subtitle: Easy to use and difficult to break.
                            copy: |
                                Lackey facilitates the Client / Agency relationship, enforcing design rules and keeping admin users on a need to know basis. No dev stuff. It’s simple, focused &amp; consistent. Most CMS's let admins pick fonts, add hex ref colours, write HTML tags, and inject content in situations where it was never intended to go. Lackey gives admins just enough power and an easy life.
                            image:
                                type: Media
                                source: img/core/lackey-cms-screenshot-2.png
                        props:
                            theme: white
                            imageAlignment: side

                    -
                        type: Block
                        template: ~/core/partials/block/copy-media
                        fields:
                            title: Freedom for designers
                            subtitle: Be creative. Not constrained
                            copy: |
                                Lackey facilitates the Client / Agency relationship, enforcing design rules and keeping admin users on a need to know basis. No dev stuff. It’s simple, focused &amp; consistent. Most CMS's let admins pick fonts, add hex ref colours, write HTML tags, and inject content in situations where it was never intended to go. Lackey gives admins just enough power and an easy life.
                            image:
                                type: Media
                                source: img/core/lackey-emblem.svg
                        props:
                            theme: blue
                            imageAlignment: center

                    -
                        type: Block
                        template: ~/core/partials/block/copy-cta
                        fields:
                            copy: Check out the Lackey UI prototype lorem ipsum dolor amet
                            backgroundImage:
                                type: Media
                                source: img/core/lackey-ui-prototype.jpg
                        props:
                            href: https://projects.invisionapp.com/d/main#/console/7548432/162252325/preview
                            buttonLabel: Let's see it then
