---
    -
        name: Demo Signup
        path: ~/core/partials/block/signup-demo
        type: block
        thumb: /img/cms/cms/svg/form.svg

    -
        name: Copy + Call-to-action
        path: ~/core/partials/block/copy-cta
        type: block
        thumb: /img/cms/cms/svg/copy.svg

    -
        name: Copy + Media
        path: ~/core/partials/block/copy-media
        type: block
        thumb: /img/cms/cms/svg/copy-image.svg
