---
    -
        name: Demo Signup
        path: ~/core/partials/block/signup-demo
        type: block
        #thumb: /img/cms/cms/svg/image.svg

    -
        name: Copy + Media
        path: ~/core/partials/block/copy-media
        type: block
        #thumb: /img/cms/cms/svg/image.svg
