---
    -
        name: Homepage Template
        path: ~/core/index
        selectable: true
        expose:
            -
                path: layout.blocks
                type: List
        props:
            headerImageXOffset: number
            headerImageYOffset: number
            headerImageSize: number
